# Generated by Django 4.2.3 on 2023-08-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_remove_task_tags_worker_phone_number_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed']},
        ),
    ]
